// This file would normally be generated by Supabase CLI
// For now, we'll create it manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          country_code: string
          settings: Json
          features: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          country_code: string
          settings?: Json
          features?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          country_code?: string
          settings?: Json
          features?: Json
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          organization_id: string
          email: string
          full_name: string
          role: 'admin' | 'ringer' | 'viewer'
          phone: string | null
          settings: Json
          last_active: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          email: string
          full_name: string
          role: 'admin' | 'ringer' | 'viewer'
          phone?: string | null
          settings?: Json
          last_active?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          email?: string
          full_name?: string
          role?: 'admin' | 'ringer' | 'viewer'
          phone?: string | null
          settings?: Json
          last_active?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      contacts: {
        Row: {
          id: string
          organization_id: string
          external_id: string | null
          full_name: string
          phone: string
          email: string | null
          address: string | null
          tags: string[]
          custom_fields: Json
          last_contact_date: string | null
          total_events_attended: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          external_id?: string | null
          full_name: string
          phone: string
          email?: string | null
          address?: string | null
          tags?: string[]
          custom_fields?: Json
          last_contact_date?: string | null
          total_events_attended?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          external_id?: string | null
          full_name?: string
          phone?: string
          email?: string | null
          address?: string | null
          tags?: string[]
          custom_fields?: Json
          last_contact_date?: string | null
          total_events_attended?: number
          created_at?: string
          updated_at?: string
        }
      }
      call_logs: {
        Row: {
          id: string
          organization_id: string
          contact_id: string
          ringer_id: string
          outcome: 'answered' | 'voicemail' | 'no_answer' | 'wrong_number' | 'disconnected'
          notes: string | null
          duration_seconds: number | null
          tags: string[]
          called_at: string
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          contact_id: string
          ringer_id: string
          outcome: 'answered' | 'voicemail' | 'no_answer' | 'wrong_number' | 'disconnected'
          notes?: string | null
          duration_seconds?: number | null
          tags?: string[]
          called_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          contact_id?: string
          ringer_id?: string
          outcome?: 'answered' | 'voicemail' | 'no_answer' | 'wrong_number' | 'disconnected'
          notes?: string | null
          duration_seconds?: number | null
          tags?: string[]
          called_at?: string
          created_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}