-- DISABLE RLS ON ALL TABLES
-- This will make all data visible to all users

ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_interactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE group_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_registrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE pathways DISABLE ROW LEVEL SECURITY;
ALTER TABLE pathway_steps DISABLE ROW LEVEL SECURITY;
ALTER TABLE pathway_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_pathways DISABLE ROW LEVEL SECURITY;
ALTER TABLE communication_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE petition_signatures DISABLE ROW LEVEL SECURITY;
ALTER TABLE phonebank_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE organization_api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE webhooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_logs DISABLE ROW LEVEL SECURITY;

-- Show confirmation
SELECT 'RLS DISABLED ON ALL TABLES!' as message;