name = "contact-manager-pwa"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Environment variables (these will be encrypted in Cloudflare)
[vars]
VITE_SUPABASE_URL = ""
VITE_SUPABASE_ANON_KEY = ""

# Preview environment (for PR previews and non-main branches)
[env.preview.vars]
VITE_DEMO_MODE = "true"

# Production environment
[env.production.vars]
VITE_DEMO_MODE = "true"
VITE_SUPABASE_URL = "https://oxtjonaiubulnggytezf.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94dGpvbmFpdWJ1bG5nZ3l0ZXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTM4ODgsImV4cCI6MjA2Mzc2OTg4OH0.9EsXc65D-5qgXLtu48d1E1Bll_AjaCt-a2-oPhZzUQU"